AWSTemplateFormatVersion: "2010-09-09"
Description: Data - S3 bucket for our data

Resources:
  DataBucket:
    Type: AWS::S3::Bucket

Outputs:
  DataBucketName:
    Value: !Ref DataBucket
  DataBucketArn:
    Value: !GetAtt DataBucket.Arn