AWSTemplateFormatVersion: "2010-09-09"
Description: data backups - backup bucket with Object Lock + policy for replication from A

Parameters:
  SourceAccountId:
    Type: String
    Description: Account ID of the source account (A)
  ReplicationRoleName:
    Type: String
    Default: s3-replication-role
  RetentionDays:
    Type: Number
    Default: 35
    MinValue: 1

Resources:
  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: COMPLIANCE
            Days: !Ref RetentionDays
      Tags:
        - Key: DataSensitivity
          Value: Public
        - Key: DataCriticality
          Value: Important # this is the backup, not the original

  BackupBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BackupBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowReplicationFromSourceRole
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${SourceAccountId}:role/${ReplicationRoleName}"
            Action:
              - s3:ReplicateObject
              - s3:ReplicateDelete
              - s3:ReplicateTags
              - s3:ObjectOwnerOverrideToBucketOwner
            Resource: !Sub "${BackupBucket.Arn}/*"

Outputs:
  BackupBucketName:
    Value: !Ref BackupBucket
  BackupBucketArn:
    Value: !GetAtt BackupBucket.Arn
